name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.5.1
  collection: ^1.15.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0
  flutter_riverpod: ^1.0.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
